### ISSUE TITLE
foundation.min.css not found

### ISSUE THREAD

**Issue by andrewheekin** [FancyPixel/small-frontend#10]
after running npm install, bower install, and gulp watch, it seems the app is expecting foundation.min.css in dist/css/ but it isn't showing up there. Any thoughts?

**Comment by noozo** [comment]
+1

**Comment by noozo** [comment]
Temporary fix (probably affects production afterwards) is to change the link and script tags in index.html to:

```
<link rel="stylesheet" href="bower_components/foundation/css/foundation.min.css">
```

and 

```
<script src="bower_components/foundation/js/foundation.min.js"></script>
```

**Comment by noozo** [comment]
Found a better way:

Change the gulpfile.js to include the following two extra tasks (put them after the "ugly hack to bring modernizr in"):

```
// Ugly hack to bring foundation js in
gulp.task('foundation-js', function() {
   return gulp.src('bower_components/foundation/js/foundation.min.js')
   .pipe(gulp.dest(p.distJs));
});

// Ugly hack to bring foundation css in
gulp.task('foundation-css', function() {
  return gulp.src('bower_components/foundation/css/foundation.min.css')
  .pipe(gulp.dest(p.distCss));
});
```

And change the gulp task that loads libs to:

```
gulp.task('libs', function() {
  gulp.start(['modernizr', 'foundation-css', 'foundation-js', 'bower-libs', 'fonts']);
});
```

Restart gulp watch.

This will copy the css and js from foundation into dist, where the index.html expects them.
