### ISSUE TITLE
css not working

### ISSUE THREAD

**Issue by MuhammadTamzid** [FancyPixel/small-frontend#11]
dist/css/foundation.min.css missing 
**viewed UI**
![css not workingscreenshot from 2016-05-20 14 27 25](https://cloud.githubusercontent.com/assets/14922233/15421794/0853bd4e-1e97-11e6-9f86-4b725e3fcc31.png)

**accepted UI**
![list](https://cloud.githubusercontent.com/assets/14922233/15421858/527e837c-1e97-11e6-9cda-ac053573886b.png)

**Comment by MuhammadTamzid** [comment]
Solved by follow this https://github.com/FancyPixel/small-frontend/issues/10

**Comment by andreamazz** [comment]
Hi @MuhammadTamzid 
Thanks for the heads up. I applied the solution in #10 to the codebase.

Cheers
