### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by hawaiifi** [FancyPixel/small-frontend#3]
When running npm install, I get the following error:

npm ERR! EEXIST, open '/var/root/.npm/1b3922e6-adable-stream-1-0-33-package-tgz.lock'
File exists: /var/root/.npm/1b3922e6-adable-stream-1-0-33-package-tgz.lock
Move it away, and try again.

When I check for the file /var/root/.npm/1b3922e6-adable-stream-1-0-33-package-tgz.lock – it doesn't exist.

**Comment by andreamazz** [comment]
Hi @hawaiifi 
That's an issue related to NPM, not this repo. My suggestion is to make sure to use the latest version of npm, and try to clean the cache:

```
npm cache clean
sudo rm -rf ~/.npm
```

**Comment by hawaiifi** [comment]
Yep, that was the issue.

Mahalo @andreamazz
