### ISSUE TITLE
POST users_path 422 - Unprocessable Entity?

### ISSUE THREAD

**Issue by tehfailsafe** [FancyPixel/small-frontend#4]
Cloning both frontend and rails repos, npm install etc and rails rake etc. 
Going to the front end and trying to register a new user gets stuck with the following console error:

`POST http://localhost:3000/v1/users 422 (Unprocessable Entity)`

which in turn throws an error in the browser:
`translation missing: en.user_create_error`

Did I miss something?

**Comment by tehfailsafe** [comment]
Well, creating the user with the rails console works, and then I can log in, but I'm curious to know what is going wrong with trying to register via the client? Devise has always been a pain point for me. 

Also I was able to get it deployed, rails to heroku and front-end to github pages.
http://tehfailsafe.github.io/small-react/index.html

I noticed an issue with the story title displaying the previous story until the new data comes down from the API. Since they are on different servers the delay is 500ms or so, and then snaps to correct title. I haven't looked into fixing it, but should it be an easy fix? I am interested in playing with this idea for a rails  app I already have running, adding comments specifically, but not sure if it's going to be best to use the api and separate front end or just go with something like `react-rails` gem. 

I like the idea of creating separation as I add new features, but not if it's a massive undertaking each time.

**Comment by andreamazz** [comment]
Hi @tehfailsafe 
The registration problem was a nasty bug on my end, you should pull the latest versions of both the rails and the react applications.  
Resetting the title should be an easy fix, I'll look into it.  

If you already have a rails app up and running the best solution is using `react-rails`, switching to this architecture will be too much of an effort.
