### ISSUE TITLE
post requests with login leads to repeated logins?

### ISSUE THREAD

**Issue by tehfailsafe** [FancyPixel/small-frontend#6]
Not sure if there is any other way for this, but checking the rails logs shows some interesting behavior. Each request is treated as a log in,  updating the user with a new timestamp for signing in, incrementing `sign_in_count` etc.  

Just from an hour or so of testing I got `["sign_in_count", 303]`.
While I'm not currently using this data for anything, I can imagine a scenario where I would want to. Is there a way to only trigger the sign in on the actual sign in, rather than each and every request?

**Comment by andreamazz** [comment]
Hi @tehfailsafe 
Since the app is not using sessions, each request lives on its own and needs to authenticate each time, it's an intended behaviour. If you don't want to update the user model at each request, you can disable the `trackable` module of Devise in the user's model.

**Comment by tehfailsafe** [comment]
Gotcha. I minimum time between tracking logins on the user model would be ideal, but that's a devise thing. Thanks for the reply, and the example app. Really helped me wrap my head around all this stuff.

**Comment by andreamazz** [comment]
Glad to hear that :+1:
Cheers
