### ISSUE TITLE
Article part 3

### ISSUE THREAD

**Issue by jgujgu** [FancyPixel/small-frontend#7]
Hi Andrea,

In the article, you declare "WebAPIUtils" in the StoryStore, StoriesPage, StoryPage, and StoryNew page. My understanding was that only the ViewActionCreators would ever touch the WebAPIUtils, with the WebActionCreators then communicating with the dispatcher. Is this correct? Should WebAPIUtils not be declared in these pages?

-Jeffrey

**Comment by andreamazz** [comment]
Hi Jeffrey. You are correct, the WebAPIUtils class should be only referenced in the action creators, for this sample I cut some corners and called the API directly in the pages, but the right way is what you described. 
Cheers :+1:
